### ISSUE TITLE
Can't find extension key in Magento connect market

### ISSUE THREAD

**Issue by jpmaligne** [hipay/hipay-fullservice-sdk-magento1#139]
Hello guys,

I want to update my Hipay module from version 1.3.6 to latest but can't find the extension key to insert in my backoffice.

The [link](http://www.magentocommerce.com/magento-connect/hipay-fullservice-1.html) provided in documentation seems to be dead.

A man needs help.
Thanks

**Comment by jprotin** [comment]
Hello,

Magento connect is closed and we are waiting the Partenaria validation with Magento to diffuse the module in the Magento Marketplace.
We are sorry the documentation about extension installation is not update yet, It is based on the old method of installation.

If you want the source code, go to the releases tab, select the latest release and download the tar.gz : 
https://github.com/hipay/hipay-fullservice-sdk-magento1/releases/tag/1.8.1 

It's a manual installation, You will extract the source code in you local machine and transfer the files throught FTP.

Many thanks

All the best.

Johan

**Comment by jpmaligne** [comment]
Roger 5/5
Thanks for the very quick response.

Keep up the good work !
