### ISSUE TITLE
Déclaration méthode incorrecte

### ISSUE THREAD

**Issue by Axel29** [hipay/hipay-fullservice-sdk-magento1#140]
La déclaration de la méthode "_getElementHtml()" de la classe "Allopass_Hipay_Block_Adminhtml_System_Config_Form_Field_ListDisabled" est incorrecte. Il manque le type du paramètre "$element" à "Varien_Data_Form_Element_Abstract" pour rendre la classe compatible avec sa classe parente.

Sans ça, une notice est déclenchée "Strict Notice: Declaration of Allopass_Hipay_Block_Adminhtml_System_Config_Form_Field_ListDisabled::_getElementHtml() should be compatible with Mage_Adminhtml_Block_System_Config_Form_Field".

**Comment by etiennelandais** [comment]
Bonjour, 

merci de votre remontée, nous allons corriger cette issue dans une des prochaines release du module.

Etienne

**Comment by etiennelandais** [comment]
https://github.com/hipay/hipay-fullservice-sdk-magento1/releases/tag/1.9.4
