### ISSUE TITLE
Hosted Iframe + Paypal : perte des données Iframe

### ISSUE THREAD

**Issue by gcann-tbd** [hipay/hipay-fullservice-sdk-magento1#141]
Bonjour, 
si le mode de paiement Hipay_Paypal est proposé après le Hipay_Hosted (via les order_id par exemple), alors les données de configuration pour l'iFrame Hosted ne sont pas appliqués.
Le template app/design/frontend/base/default/template/hipay/form/hosted.phtml appliqué dans les 2 cas possède un code JS qui ne tient pas compte du mode de paiment sélectionné et se retrouve donc configuré avec les infos du dernier mode de paiement de la liste.
La récupération des données d'iFrame doit se faire par méthode de paiement (code), et la fonction JS "Review.prototype.displayIframe" doit utiliser les données correspondantes au paiement choisi.

**Comment by jprotin** [comment]
Bonjour Gerald,

Merci pour ta remonté, on check çà rapidement pour la release fin de semaine prochaine.

Bonne journée !

**Comment by etiennelandais** [comment]
Bonjour, 

Le bug a été corrigé dans la derniére version du module :
 https://github.com/hipay/hipay-fullservice-sdk-magento1/releases/tag/1.9.4
