### ISSUE TITLE
Wrong email language

### ISSUE THREAD

**Issue by alex5513** [hipay/hipay-fullservice-sdk-magento1#142]
Hi,

When I switch my language on front and i use Hipay as payment method, I receive my order confirmation email in the wrong language (default language). 
With other payment methods, no problems.

Alexis

**Comment by etiennelandais** [comment]
Hello !

Thanks you for briging this issue but we rely on the magento core to send the order confirmation mail. 
I think it's more likely an magento core issue.

It might be related to https://magento.stackexchange.com/questions/25612/cron-job-template-block-not-being-translated-but-testobserver-is

regards,
