### ISSUE TITLE
AddToCart redirige sur l'iframe de paiement

### ISSUE THREAD

**Issue by gcann-tbd** [hipay/hipay-fullservice-sdk-magento1#146]
Dans le cas de l'utilisation d'une iframe pour afficher le formulaire de paiement (HostedController), l'url de paiement : <mon site>/hipay/hosted/sendRequest/ est stockée dans la session du checkout.
Cependant, rien n'empêche l'utilisateur d'aller sur une autre page, page produit par exemple, et de cette page refaire un ajout au panier.
Hors l'ajout au panier vérifie la présence d'une url dans la session et redirige vers cette url.
Du coup, au lieu d'une redirection _"classique"_ vers le panier, la redirection se fait sur le _"sendRequest"_ et _**affiche du coup le formulaire Hipay (iframe) en pleine page**_.
Une solution a été de placer ce code :
        `Mage::getSingleton('checkout/session')->setRedirectUrl(null);`
avant le 
        `$this->_redirectUrl($redirectUrl);`
de la méthode "sendRequestAction", classe : "Allopass_Hipay_Controller_Payment"

En attendant votre retour, cette modification a été placée via copie du fichier en local pour ne pas modifier le module directement : app/code/local/Allopass/Hipay/Controller/Payment.php

**Comment by gcann-tbd** [comment]
Issue ouverte trop rapidement....effet de bord d'un autre module désolé.

**Comment by jprotin** [comment]
ahah pas de soucis Gerald !

Merci en tout cas pour votre activité sur la contribution du module !

Johan
