### ISSUE TITLE
Mise à jour de sécurité augmentant la longueur des tokens 

### ISSUE THREAD

**Issue by thomascharbit** [hipay/hipay-fullservice-sdk-magento1#147]
Bonjour,

Suite à l'annonce https://support.hipay.com/hc/fr/articles/360002489179-Importante-mise-%C3%A0-jour-de-s%C3%A9curit%C3%A9-augmentant-la-longueur-des-tokens je me pose quelques questions :)

Est-ce que cela a une impact sur l'utilisation de ce module ? Quelle(s) méthode(s) de paiement est impactée (j'utilise HiPay Enterprise Credit Card Hosted Page) ?

Si le module est bien compatible, depuis quelle version ?

Merci d'avance !

**Comment by jprotin** [comment]
Bonjour @thomascharbit ,

L'impact est qu'il faut s'assurer d'être à jour sur votre module Magento 1 pour la nouvelle gestion des tokens sur la plate-forme HiPay.
Bien sur que le module est compatible mais quand ce genre d'évolution lié à la sécurité arrive, nous préférons prévenir de mettre à jour.
Si vous utilisez les Hosted Pages et le one-click, la taille du token enregistré change, mais nativement le module Magento 1 anticipait cette nouvelle taille du token donc aucun soucis.
Pour des raisons de sécurité, nous préférons que les marchands mettent leur module HiPay à jour.

Bonne semaine et merci !

**Comment by thomascharbit** [comment]
Merci,

Je comprend la démarche mais j'ai reçu un email à ce sujet le 21 février pour une mise en production le 28.. C'est trop court pour mettre à jour, tester, déployer sur plusieurs sites !
Si nous savions quelle version permet de fonctionner sans risque cela permettrait de prévoir une mise à jour sans précipitation..

**Comment by jprotin** [comment]
Bonjour @thomascharbit 

Normalement vous avez été notifié par email le **18/01**, un rappel le **01/02** et un deuxième rappel le **21/02**.
Je pense que depuis le 18/01 ( 1 mois et demie ) , vous avez eu le temps de mettre à jour le module HiPay afin de profiter des nouvelles fonctionnalités, des bugfix et des fixes de sécurité. :)
Dans votre premier message, vous dites être en mode Hosted page, donc vous n'avez pas trop d'impact.
L'impact est comme je le disais sur la gestion du one-click en mode Hosted page où le module HiPay stocke en base de données le token de la carte de vos clients, car la taille du token a évolué pour plus de sécurité. Le module est open source et donc il peut-être modifier par nos marchands comme ils le souhaitent et nous préférons s'assurer qu'ils migrent vers la dernière version du module HiPay.
Si vous êtes sur une version qui date de plus d'un ou deux ans, je vous conseille vivement de mettre à jour votre module !

Je vous invite grandement à contacter le support HiPay pour toutes autres informations : support@hipay.com

Merci beaucoup

Johan PROTIN

**Comment by thomascharbit** [comment]
Je m'excuse je ne connaissais pas cette timeline qui parait plus logique..

Merci pour vos réponses
