### ISSUE TITLE
OrderRequestAbstract formatter ignores getConfigPaymentAction overriding  

### ISSUE THREAD

**Issue by alenalato** [hipay/hipay-fullservice-sdk-magento1#149]
Version 1.13.1
In file `app/code/community/Allopass/Hipay/Model/Api/Formatter/Request/OrderRequestAbstract.php` `$orderRequest->operation` is determined based on `paymentMethod` config data instead of calling its public method `getConfigPaymentAction` (like other components do), so any customization of payment action done by overriding it is ignored, leading to inconsistent behavior.
Use case:
Config payment action is Capture.
`MyMethod::getConfigPaymentAction` overrides `Hosted::getConfigPaymentAction` to return Authorize for certain custom cases.
Transaction will be always formatted (and thus executed) as a Sale operation.

**Comment by jprotin** [comment]
Hi @alenalato ,

We will analyze your issue and we will answer you very quickly.

Many thanks.

Best.

**Comment by etiennelandais** [comment]
https://github.com/hipay/hipay-fullservice-sdk-magento1/releases/tag/1.13.3
