### ISSUE TITLE
Mauvaises dates SplitPayment

### ISSUE THREAD

**Issue by JulesLeynaud** [hipay/hipay-fullservice-sdk-magento1#152]
Lorsqu'un splitpayment est créé entre minuit et 2h heure d'été (1h heure d'hiver), et que l'unité de période est le mois, le calcul de la date des prochaines échéances n'est pas bon.
Cela semble venir d'un bug dans Zend_Date, mais celui-ci n'était pas voué à évolué sur Magento 1, il faudrait le contourner ici.

Pour cela, on peut supprimer l'heure de la Zend_Date utilisée pour le calcul. En remplaçant 
https://github.com/hipay/hipay-fullservice-sdk-magento1/blob/f52a94226ee1b355fa69f333ff6bb2560a65b824/src/app/code/community/Allopass/Hipay/Helper/Data.php#L159 par
``` php
$todayClone = new Zend_Date($todayDate->toString('yyyy-MM-dd'));
```

Pour reproduire le bug :
``` php
//Hors periode 00h - 02h (UTC+2) OK
$todayDate = new Zend_Date('2020-04-30T12:10:00+02:00');
$todayClone0 = clone $todayDate;
$dateToPay0 = $todayClone0->addMonth(0)->getDate(); // 2020-04-30 : OK
$todayClone1 = clone $todayDate;
$dateToPay1 = $todayClone1->addMonth(1)->getDate(); // 2020-05-30 : OK

//Dans periode 00h - 02h (UTC+2) KO
$todayDate = new Zend_Date('2020-04-30T00:10:00+02:00');
$todayClone0 = clone $todayDate;
$dateToPay0 = $todayClone0->addMonth(0)->getDate(); // 2020-04-01 : KO
$todayClone1 = clone $todayDate;
$dateToPay1 = $todayClone1->addMonth(1)->getDate(); // 2020-05-01 : KO

//Correction propsée, on supprime l'heure de la date du clone pour le calcul
$todayDate = new Zend_Date('2020-04-30T00:10:00+02:00');
$todayClone0 = new Zend_Date($todayDate->toString('yyyy-MM-dd'));
$dateToPay0 = $todayClone0->addMonth(0)->getDate(); // 2020-04-30 : OK
$todayClone1 = new Zend_Date($todayDate->toString('yyyy-MM-dd'));
$dateToPay1 = $todayClone1->addMonth(1)->getDate(); // 2020-05-30 : OK
```

**Comment by legithubdeaymeric** [comment]
Merci pour le feedback !

Nous allons regarder ça et probablement fixer l'issue.
Pour information, nous arrêtons le support du module Magento 1 le **30 Juin 2020**.

**Comment by luigifab** [comment]
Il y a une solution à la fin de Magento, c'est [Openmage](https://github.com/OpenMage/magento-lts) :)

**Comment by JBaptisteLvt** [comment]
Bonjour,

L'issue a été corrigée dans la version [1.15.0](https://github.com/hipay/hipay-fullservice-sdk-magento1/releases/tag/1.15.0) du module.

Bonne journée !
