### ISSUE TITLE
AMEX payments not moving to complete status?

### ISSUE THREAD

**Issue by thomascharbit** [hipay/hipay-fullservice-sdk-magento1#51]
Hi,

i have an issue using HiPay Fullservice module with AMEX payments, unsure if this the right place to get some feedback on this.

Issue is, Magento doesn't change order state to "complete" after shipping if the payment was made with AMEX card.
It works with VISA/MASTERCARD.

Please find below screenshots for two orders

### Order 200000688 (VISA):
![200000688](https://cloud.githubusercontent.com/assets/1705793/20832019/2ba1b1bc-b888-11e6-9125-25c8314aca8b.jpg)

### Order 200000689 (AMEX):
![200000689](https://cloud.githubusercontent.com/assets/1705793/20832020/2d4ceb8a-b888-11e6-8890-148f8427e40a.jpg)

Note that both orders were in "processing" status and invoiced when the shipment was made.

Is there any reason why Magento would not want to complete an order with AMEX payment?

I noticed one difference: some HiPay notifications arrive after the order was moved to "processing" state with AMEX, unlike VISA/MASTERCARD

Thanks for your help!

**Comment by jprotin** [comment]
Hi Thomas,

Can you show me your payment configuration ?
The field " Hipay status to validate order ".

Contact me at jprotin@hipay.com
