### ISSUE TITLE
Fatal error on PHP 5.4

### ISSUE THREAD

**Issue by xxorax** [hipay/hipay-fullservice-sdk-magento1#75]
On PHP 5.4.45, with v1.5, I got this error in admin :
```
PHP Fatal error:  Can't use function return value in write context in app/code/community/Allopass/Hipay/Helper/Data.php on line 617
```
Thanks

**Comment by legithubdeaymeric** [comment]
Hello,
Thanks for your feedback.
We have fixed this problem with our latest version 1.6.0

Do not hesitate to contact us if there are still errors.

Regards,

**Comment by Seb2nim** [comment]
Same error accessing methods in back office on v1.7.2 with php 5.4.45
Allopass_Hipay_Model_Method_Abstract on line 1221 and then 1634
I've checked all other usages of "empty". All Clear

[magento_community_PATCH_allopass_hipay.patch.txt](https://github.com/hipay/hipay-fullservice-sdk-magento1/files/1213071/magento_community_PATCH_allopass_hipay.patch.txt)

**Comment by legithubdeaymeric** [comment]
Thanks for your feedback.
We apply your patch for the next release.
